name: MLproject
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - pyyaml
  - ipykernel
  - pytest
  - mlflow
  - dvc
  - setuptools
  - pip
  - catboost
  - xgboost
  - pip:
    - dvc-gdrive